name: Update README

on:
  push:
    branches:
      - main # Runs on every push to the main branch

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Go
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22.6" # Update with your Go version

      # Step 3: Run the Go script to update README.md
      - name: Update README
        run: go run update-readme/update-readme.go

      # Step 4: Commit and push changes
      - name: Commit and push changes
        run: |
          git config --global user.name "RohanKhatua"
          git config --global user.email "contact@rohankhatua.dev"
          git add readme.md
          git commit -m "Update README.md with LOC data"
          git push
