name: Update README
on:
  push:
    branches:
      - main
jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Fetch LOC data and update README.md
        run: |
          # Fetch LOC data from Codetabs API
          LOC_DATA=$(curl -s "https://api.codetabs.com/v1/loc/?github=rohankhatua/asteroid&branch=main")
          echo "Fetched LOC data: $LOC_DATA"

          # Create a temporary file for the table
          TABLE_FILE=$(mktemp)

          # Write header to temp file
          echo "| Language | Files | Lines | Blanks | Comments | Lines of Code |" > "$TABLE_FILE"
          echo "|----------|-------|-------|---------|-----------|---------------|" >> "$TABLE_FILE"

          # Process each line of data and write to temp file
          echo "$LOC_DATA" | jq -c '.[]' | while read -r line; do
            LANG=$(echo "$line" | jq -r '.language')
            FILES=$(echo "$line" | jq -r '.files')
            LINES=$(echo "$line" | jq -r '.lines')
            BLANKS=$(echo "$line" | jq -r '.blanks')
            COMMENTS=$(echo "$line" | jq -r '.comments')
            LOC=$(echo "$line" | jq -r '.linesOfCode')
            
            echo "| $LANG | $FILES | $LINES | $BLANKS | $COMMENTS | $LOC |" >> "$TABLE_FILE"
          done

          # Read the generated table
          TABLE=$(<"$TABLE_FILE")

          # Clean up temp file
          rm "$TABLE_FILE"

          # Use awk to handle the replacement with proper newlines
          awk -v table="$TABLE" '
          /<!---start--->/ {
            print;
            print "";
            print table;
            print "";
            next;
          }
          /<!---end--->/ {
            print;
            next;
          }
          !/<!---start--->/ && !/<!---end--->/ {
            print;
          }
          ' readme.md > readme.tmp && mv readme.tmp readme.md

          # Verify the update
          cat readme.md

      - name: Commit and push changes
        run: |
          git config --global user.name "RohanKhatua"
          git config --global user.email "contact@rohankhatua.dev"
          git add readme.md
          git commit -m "Update README.md with LOC data"
          git push
